### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by qingmuhy** [MikeWang000000/Natter#10]
1. 因为原理所限，每次都是随机端口的，如果运营商重新拨号了，端口号也是会改变的，因此建议集成一些通知API（bark TG机器人 Server酱......），达到可以变换提醒的功能。
2. 希望最好能考虑换个语言.....因为一些嵌入式设备的存储空间其实很紧缺的，Python这种解释型语言不是很适合这些嵌入式设备，因为需要很大的空间装解释器，当然也可能是我技术能力的问题。

第一个希望能搞出来，第二个就比较随意了，**最近忙着准备很重要的考试，不然我就打算自己缝合一下了。**

主要一开始没想到这个思路搞内网穿透，还是要谢谢你花费自己的时间捣鼓这么个工具。

**Comment by qingmuhy** [comment]
这个功能让我想到了一些很不错的用途，可以在客户端没有软件安装需求的情况下暴露端口的话，兼容性会很好。

就意味着在没有公网V6的情况下也可以通过暴露的端口连VPN回家里内网了，在学校等网络环境不可控的环境及移动端设备非常有用。

在没有V6的情况下一直是用zerotier穿透回内网的，但是Zerotier穿透在移动端会遇到**回内网OR富强二选一的窘境**，如果内网穿透可以直接通过暴露端口实现的话，就可以用Clash进行分流了，这样会灵活很多。

**Comment by qingmuhy** [comment]
翻了下下面的issue貌似已经有人提出类似问题了，尴尬了，提了重复的问题了。

**Comment by qingmuhy** [comment]
也许内存不够意味着我要换路由器了，老古董了，只有16M的ROM。

**Comment by MikeWang000000** [comment]
第一个会有的。

第二个是因为我个人精力有限，毕竟还有需要加班的工作，所以基本只在周末更新。使用C需要考虑各种系统的移植，我没有这个精力。如果有人愿意使用 C 重写 Natter，我非常感激。使用 Go 可以静态编译，但编出来的二进制文件需要的空间比 Python 更大。

关于Python，此脚本已经精简到只需要 `opkg install python-light` 就能运行了，Stun 协议、HTTP 请求都是手写的，没有任何依赖，一般安装下来占用不会超过 2MB 。而且，拥有Python环境还能自己拓展各种想要的功能。

**Comment by wenpo1975** [comment]
> 第一个会有的。
> 
> 第二个是因为我个人精力有限，毕竟还有需要加班的工作，所以基本只在周末更新。使用C需要考虑各种系统的移植，我没有这个精力。如果有人愿意使用 C 重写 Natter，我非常感激。使用 Go 可以静态编译，但编出来的二进制文件需要的空间比 Python 更大。
> 
> 关于Python，此脚本已经精简到只需要 `opkg install python-light` 就能运行了，Stun 协议、HTTP 请求都是手写的，没有任何依赖，一般安装下来占用不会超过 2MB 。而且，拥有Python环境还能自己拓展各种想要的功能。

加个多端口吧哈哈

**Comment by gdy666** [comment]
> 第一个会有的。
> 
> 第二个是因为我个人精力有限，毕竟还有需要加班的工作，所以基本只在周末更新。使用C需要考虑各种系统的移植，我没有这个精力。如果有人愿意使用 C 重写 Natter，我非常感激。使用 Go 可以静态编译，但编出来的二进制文件需要的空间比 Python 更大。
> 
> 关于Python，此脚本已经精简到只需要 `opkg install python-light` 就能运行了，Stun 协议、HTTP 请求都是手写的，没有任何依赖，一般安装下来占用不会超过 2MB 。而且，拥有Python环境还能自己拓展各种想要的功能。

感谢大佬 这个项目提供的方向,我用golang做了相同的穿透功能,支持自定义在IP变化后调用第三方API接口.
https://github.com/gdy666/lucky

**Comment by MikeWang000000** [comment]
> 感谢大佬 这个项目提供的方向,我用golang做了相同的穿透功能,支持自定义在IP变化后调用第三方API接口. https://github.com/gdy666/lucky


欢迎 Go 语言移植！
<sup>不过我没有在你的库里找到这个功能的相关代码</sup>

**Comment by gdy666** [comment]
> > 感谢大佬 这个项目提供的方向,我用golang做了相同的穿透功能,支持自定义在IP变化后调用第三方API接口. https://github.com/gdy666/lucky
> 
> 欢迎 Go 语言移植！ 不过我没有在你的库里找到这个功能的相关代码

因为我没发布最新二进制程序版本的源码,主要使用了现成的库.
https://github.com/pion/stun
其它就剩细节体力活了...
