### ISSUE TITLE
ipv6可以打洞吗

### ISSUE THREAD

**Issue by fbion** [MikeWang000000/Natter#11]
ipv4 only vps通过wgcf连接cloudflare warp
但只是获得了访问ipv6网络的功能
并没有获得一个别人可以访问我的ipv6功能?

**Comment by MikeWang000000** [comment]
抱歉，Natter不会考虑支持 IPv6，原因有以下几点：

1. 理论上 IPv6 不应该使用 NAT 技术，因此需要使用 IPv6 NAT 的场景非常有限；
2. IPv6 不能接受传入连接，多数是因为防火墙的原因导致的。Natter 仅对于 NAT 环境做处理，而对于防火墙没有任何办法；
3. 很少有 IPv6 的公共 STUN 服务器。

我没有使用过这个 CloudFlare 的服务，但是我认为这应该不是 NAT 问题导致的。

**Comment by MasterOfStar** [comment]
CloudFlare的WARP作为一种隐私保护VPN，下发分配的是NAT后的ULA ip。
而且没记错是Symmetric NAT来着。

_而且如果是要ipv6的话为什么不用HE的隧道呢？_
