### ISSUE TITLE
请允许手动指定测试IP端口

### ISSUE THREAD

**Issue by muink** [MikeWang000000/Natter#13]
希望添加选项能够手动指定测试 IP/PORT 而不是默认的 `0.0.0.0:0`

**Comment by MikeWang000000** [comment]
你好👋！Natter 中使用的 STUN 服务器均使用标准端口 TCP/UDP 3478。
https://github.com/MikeWang000000/Natter/blob/384cea0e84cb37c7d6d1d7f57e4f0c885b7888de/natter.py#L77

当前版本下，您可以在以下代码中更改 STUN 服务器列表。

https://github.com/MikeWang000000/Natter/blob/384cea0e84cb37c7d6d1d7f57e4f0c885b7888de/natter.py#L59-L75

**Comment by muink** [comment]
@MikeWang000000 
是我表达错误了, 我并不是要使用非标准端口的STUN服务器
我是需要手动指定**Src.IP/PORT**朝STUN服务器发送测试(类似[NatTypeTester](https://github.com/HMBSbige/NatTypeTester))
因为我的网络环境是顶层路由另有他人使用, 我能够设置端口转发, 但是不可能设置DMZ把所有端口转到我自己的二层路由上(因为他也要用部分端口)
所以使用[Natter](https://github.com/MikeWang000000/Natter)的随机端口只会得到**Symmetric**的结果

**Comment by MikeWang000000** [comment]
我预留了这个功能，但没有加上去。
作为临时处理，可以改成 `check_nat_type(端口号) `

https://github.com/MikeWang000000/Natter/blob/384cea0e84cb37c7d6d1d7f57e4f0c885b7888de/natter.py#L471
