### ISSUE TITLE
测试 win10 远程也可以,一些建议

### ISSUE THREAD

**Issue by aeeq** [MikeWang000000/Natter#15]
1.设置 dmz 主机
2.先关闭远程，否则开 natter 会失败
3运行 python.exe .\natter.py  127.0.0.1 3389
4.开启远程，就可以用 natter 返回的 ip 端口远程了

可否做到不用关闭，直接运行

现在直接运行提示错误  [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

经过多次测试，建议 forward_port 里可以定义监听端口，那么主路由不用开dmz ,只要做这个端口的映射就可以了

例如 主机A ip 192.168.1.8
        远程端口 192.168.1.8

"forward_port": {
        "tcp": [
           "192.168.1.8:3389"
        ],"udp": [
        ]
    }
我临时改了 get_free_port 里面 sock.bind(("", 0)) 成 sock.bind(("", 8002))
那么路由器里做好 8002 端口映射就可以了,不用开 dmz
建议这个 8002 可以在 forward_port 里自定义，这样子就灵活了

**Comment by sparkssssssss** [comment]
试试
python.exe natter.py  13389
然后,路由器上做一个端口映射 an:13389 -> winip:3389

**Comment by wangx2** [comment]
我出现了第一天可以连接，但是隔天就不行了，我查了一下端口是开放状态的，但是mstsc就是报错
![image](https://user-images.githubusercontent.com/16116338/233517976-7f4c0ee1-b81b-4b6a-aa30-a0a8d734c78e.png)
