### ISSUE TITLE
发现一个新的stun服务器，不知道是不是公开的

### ISSUE THREAD

**Issue by zxbiao** [MikeWang000000/Natter#16]
RT~
上海艾泰旗下的
地址是
`stun.greenwifi.com.cn`

**Comment by MikeWang000000** [comment]
简单的一个测试：
```
sudo apt install stuntman-client
```

```
~ $ stunclient stun.greenwifi.com.cn
Binding test: fail
```

```
~ $ stunclient --protocol tcp stun.greenwifi.com.cn
Can't connect to server (hr == 8800006e)
```

看起来 UDP 和 TCP 下均不可用。

**Comment by zxbiao** [comment]
> 简单的一个测试：
> 
> ```
> sudo apt install stuntman-client
> ```
> 
> ```
> ~ $ stunclient stun.greenwifi.com.cn
> Binding test: fail
> ```
> 
> ```
> ~ $ stunclient --protocol tcp stun.greenwifi.com.cn
> Can't connect to server (hr == 8800006e)
> ```
> 
> 看起来 UDP 和 TCP 下均不可用。

感谢回复和测试，如何是这样，恐怕是非公开的。
我是在艾泰的企业级路由器配合adguardhome查DNS查询发现出来的。

**Comment by MikeWang000000** [comment]
> 感谢回复和测试，如何是这样，恐怕是非公开的。 我是在艾泰的企业级路由器配合adguardhome查DNS查询发现出来的。

可能这个 STUN 服务器是带有认证的，或者是白名单IP才可访问。
通过伪造来源地址是可以利用 STUN 服务器向特定地址发起流量攻击的，因此一些企业选择拒绝公网上的 STUN 请求也挺常见。
