### ISSUE TITLE
内置的服务器 stun.stunprotocol.org 是错的

### ISSUE THREAD

**Issue by flynaj** [MikeWang000000/Natter#25]
stun.stunprotocol.org 正确的服务器是 stunserver.stunprotocol.org

**Comment by MikeWang000000** [comment]
这个是已知问题，不过我暂时没有打算更新，是因为这个服主由于遭受过高的流量而付了4000刀的高额账单(ref: https://t.co/xLcwfVJz9O)，从而更改了域名。
同时由于Natter的候选机制，Natter会忽略这个问题尝试下一个服务器。
过一段时间我会评估是替换一个新的公共STUN服务器，还是直接去除：）

**Comment by MikeWang000000** [comment]
v2 版本中已经更新。
