### ISSUE TITLE
openwrt 上出现这个错误提示，何解？

### ISSUE THREAD

**Issue by pop2006** [MikeWang000000/Natter#26]
看了青木幻境的文章
https://qingmuhy.com/index.php/archives/71/
就照着在openwrt上跑了一下，出现这个提示，特来请教。
python natter.py 80
  File "/root/natter.py", line 74
    <title>Natter/natter.py at master · MikeWang000000/Natter · GitHub</title>
                                      ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by MikeWang000000** [comment]
Python文件下载错误，您下载到的是HTML源码。
请尝试重新下载再试。
