### ISSUE TITLE
OpenWrt是旁路由如何配置防火墙规则打洞

### ISSUE THREAD

**Issue by ZhelinCheng** [MikeWang000000/Natter#29]
我脚本运行在OpenWrt上的，主路由是iKuai，OpenWrt是旁路由；
在关闭OpenWrt的防火墙后，是能成功运行的；

不关闭防火墙：
NAT Type for UDP: [ Full cone (NAT 1) ]
NAT Type for TCP: [ Symmetric ]

但是关闭了防火墙后就无法访问外网了，不知道大佬知不知道如何配置这个防火墙规则。

**Comment by MikeWang000000** [comment]
可以尝试使用最新 v2 版本，现在可以通过 `-m iptables` 自动创建 iptables 规则了。

另外 Natter 与 “透明代理” 确实相冲突，因为代理会改变 NAT 类型，并且可能改变出口 IP。
防火墙可以考虑放过 STUN 的 3478 端口不走代理，并且放过保活服务器的 IP 。
