### ISSUE TITLE
测试成功后去掉t，似乎无法转发到指定服务端口上

### ISSUE THREAD

**Issue by remember19890604** [MikeWang000000/Natter#3]
加t时显示it works，去掉t把这个端口转发到本机其他http，似乎不行

**Comment by MikeWang000000** [comment]
后面我会在 Natter 自身集成转发功能，有空时我会更新一下~

**Comment by wenpo1975** [comment]
> 加t时显示it works，去掉t把这个端口转发到本机其他http，似乎不行

我直接去掉-t不行，加上-v可以。
即python natter.py -v 3456

**Comment by zhezhe168** [comment]
> > 加t时显示it works，去掉t把这个端口转发到本机其他http，似乎不行
> 
> 我直接去掉-t不行，加上-v可以。 即python natter.py -v 3456

你的转发规则是怎么写的，可以贴一下么

**Comment by zhezhe168** [comment]
> 后面我会在 Natter 自身集成转发功能，有空时我会更新一下~

大佬，不好意思，是我端口转发没设置好，测试是正常的

**Comment by MikeWang000000** [comment]
> 大佬，不好意思，是我端口转发没设置好，测试是正常的

没事的，是我没有在说明里面说清楚，现在更新 readme 了。

**Comment by MikeWang000000** [comment]
最新 v2 版本中已经加入各种转发方法，详见：
https://github.com/MikeWang000000/Natter/blob/master/docs/forward.md
