### ISSUE TITLE
0.9版本 udp洞的端口不会在运营商改变公网ip时自动更新

### ISSUE THREAD

**Issue by muink** [MikeWang000000/Natter#30]
wan口是路由接入, 所以接口不会down, 接口的ip也不会变, 但是上级光猫隔一段时间 (可能是几天) 公网ip会变
变动后查看`natter-status.json`
tcp洞会自行更新端口, 而udp洞还依然保持着旧端口没有更新
所有洞都是`open_port`洞

**Comment by MikeWang000000** [comment]
最新 v2 版本修正了 UDP 的问题，可以尝试一下。
