### ISSUE TITLE
关于运营商 NAT 类型的疑问，宽带突然从 NAT 1 变成 NAT 3

### ISSUE THREAD

**Issue by lyc8503** [MikeWang000000/Natter#36]
坐标苏州移动，之前尝试过使用 Natter 和 natmap 进行打洞，使用一切正常，连接稳定，正常使用了约半年，NAT 类型测试一直是 NAT 1 (Fullcone)。

突然一天晚上发现连接失败了，排查后发现 NAT 类型变为 3 (Port-restricted Cone)，无法打洞，期间一直没有修改过 OpenWRT 路由和光猫的相关配置，尝试过重启光猫和路由器无果。且本地另一条同套餐的移动宽带 NAT 类型仍然是 NAT 1，不知道为什么这条突然变成了 NAT 3。

不知道是否有相关的先例，有什么可能的原因或排查方向吗？
（之后我可能试试查看下光猫配置或联系移动客服，但现在不在设备边上不太方便）

**Comment by lyc8503** [comment]
```
root@OpenWrt:~# python3 natter_check.py 
> NatterCheck v2.0.0-rc1

Checking TCP NAT...                  [  FAIL  ] ... NAT Type: 3
Checking UDP NAT...                  [  FAIL  ] ... NAT Type: 3
```

在 OpenWRT 上的测试结果如图，OpenWRT 本身的 Firewall 已经放行 `wan -> This Device` 的所有流量，应该不是设备本身防火墙导致的问题？

**Comment by MikeWang000000** [comment]
光猫是否为路由模式？运营商可以向光猫远程下发配置，用户可能并不知情。
建议检查光猫防火墙。

**Comment by lyc8503** [comment]
我 OpenWRT 上设置的仍为 PPPoE 拨号，且拨号成功，如果光猫侧直接下发配置改为路由模式，理论上我 OpenWRT 也要对应改为 DHCP 获取地址？ 

我周末线下去看看光猫的拨号和防火墙相关配置。

**Comment by MikeWang000000** [comment]
如果 OpenWRT 是 PPPoE 拨号测得的结果，那么 NAT 3 基本上可以确定是运营商侧改动网络了，用户侧没有办法。

**Comment by lyc8503** [comment]
拿电脑拨号后测试也是 NAT 3，正在和移动客服联系...

**Comment by lyc8503** [comment]
应该是上传量过大后被误判了 PCDN，和移动客服联系，移动工作人员上门检查后恢复了 NAT 1

https://www.v2ex.com/t/1010906

Natter 和 Natmap 又都能用了，感谢作者的软件！
