### ISSUE TITLE
[Windows] STUN servers unreachable on UDP mode in v2 version

### ISSUE THREAD

**Issue by InoriILU** [MikeWang000000/Natter#37]
大哥打扰了，v2版本下无法使用udp打洞，每一个stun服务器都无响应。
![图片](https://github.com/MikeWang000000/Natter/assets/89334352/4c24e268-365b-450b-adb7-f4cbb08e210c)
但是当使用其他nat测试软件时相同的服务器有所响应。
![图片](https://github.com/MikeWang000000/Natter/assets/89334352/4a29d2a1-ea53-4cf9-89ce-6b071dd2546f)

**Comment by MikeWang000000** [comment]
感谢汇报。看起来这是个 Windows 上特有的问题，请等待修复。

**Comment by MikeWang000000** [comment]
看起来是因为 Windows 下端口复用的表现与 Linux 不同导致的。
我在 `dev` 分支进行了一个临时的修复，看看是否解决了此问题？（我不常用 Windows）

https://github.com/MikeWang000000/Natter/blob/dev/natter.py

**Comment by InoriILU** [comment]
可。
本地：
![图片](https://github.com/MikeWang000000/Natter/assets/89334352/edc2a118-fd33-4460-b333-922e6031cf97)
![2024-01-21](https://github.com/MikeWang000000/Natter/assets/89334352/4bc4a71b-fac9-4c33-98f2-071baa40d640)
远程：
![Screenshot_2024-01-21-12-00-18-445_com microsoft](https://github.com/MikeWang000000/Natter/assets/89334352/7baed8ec-7617-4486-9e6e-2733395dceb3)

**Comment by MikeWang000000** [comment]
Fixed by 48f5a6e.
