### ISSUE TITLE
natter_checker.py 中，ip changed 判断似乎有问题

### ISSUE THREAD

**Issue by KKRainbow** [MikeWang000000/Natter#39]
L241 ip_changed   = (recv_host != self.STUN_PORT)

应该跟 stun_host 比较

**Comment by MikeWang000000** [comment]
此代码本意用于判断 STUN 服务器是否真的支持切换 IP 或 端口，这里确实是我的笔误。

您是否愿意提一个 PR？

**Comment by KKRainbow** [comment]
可以

**Comment by MikeWang000000** [comment]
Fixed by deee2fe.
我加上 Co-author 了。
