### ISSUE TITLE
提供查询接口

### ISSUE THREAD

**Issue by ahlixinjie** [MikeWang000000/Natter#6]
提供接口能查询到目前的公网ip:port  这样我好在其他应用里进行通知

**Comment by MikeWang000000** [comment]
可以。后面会加上 `-f FILE` 选项将公网地址写入文件。

**Comment by wenpo1975** [comment]
我也觉得。单独新建一个txt日志
最好ServerChan之类的推送一下
这样直接写个脚本让他开机自动运行就好了

**Comment by MikeWang000000** [comment]
> 我也觉得。单独新建一个txt日志
> 最好ServerChan之类的推送一下
> 这样直接写个脚本让他开机自动运行就好了

如果会 Python 的话可以手改，源代码有下面两处是获得本地地址和公网地址的。
考虑到 OpenWRT 等设备本身闪存不够大，Natter 还是以最小依赖为原则，不引入过多的依赖了。

（自用随便改，公开需要遵守GPL）

https://github.com/MikeWang000000/Natter/blob/2d8ddb2b88c02caf84253fbd7edafa91ab286cfe/natter.py#L502
https://github.com/MikeWang000000/Natter/blob/2d8ddb2b88c02caf84253fbd7edafa91ab286cfe/natter.py#L530

**Comment by ahlixinjie** [comment]
> 可以。后面会加上 `-f FILE` 选项将公网地址写入文件。

搞文件有点麻烦了0.0, 不是提供了http server么,  感觉直接给个接口会好点,  可以的话有时间我提个mr

**Comment by MikeWang000000** [comment]
> 搞文件有点麻烦了0.0, 不是提供了http server么, 感觉直接给个接口会好点, 可以的话有时间我提个mr

一切皆文件（确信）
当然您能提供方案是最好的，欢迎贡献！

**Comment by ahlixinjie** [comment]
> > 搞文件有点麻烦了0.0, 不是提供了http server么, 感觉直接给个接口会好点, 可以的话有时间我提个mr
> 
> 一切皆文件（确信） 当然您能提供方案是最好的，欢迎贡献！

没事, 你有想法就行, 我能用就可以

**Comment by YYQHoro** [comment]
此PR已实现文件接口
https://github.com/MikeWang000000/Natter/pull/17

**Comment by MikeWang000000** [comment]
根据多种方式的实验，最终 v2.0 版本决定使用通知脚本形式主动推送相关信息，不再支持从 Natter 查询拉取。
