### ISSUE TITLE
可以开udp吗

### ISSUE THREAD

**Issue by fbion** [MikeWang000000/Natter#7]
帮助 Full cone NAT (NAT 1) 用户打开公网 UDP 端口。

**Comment by MikeWang000000** [comment]
后面会加上这个功能。
我写了个粗糙的 demo，跑 wireguard 是没有问题的。

因为 UDP 是无连接的，端口重用会混跑 STUN 协议和另外一个协议。
考虑到这点，我会把功能实现稳定下来之后，加到 Natter 里面。

**Comment by bfmtbbs** [comment]
我用v0.9确实可以打开udp端口， 但是如果先打开wireguard在运行natter ，会提示：
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
反之也是一样，wireguard报错无法使用同端口
而TCP却是可以同时运行natter和应用程序使用相同端口的，这个可以解决吗？

**Comment by MikeWang000000** [comment]
> 我用v0.9确实可以打开udp端口， 但是如果先打开wireguard在运行natter ，会提示： OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 反之也是一样，wireguard报错无法使用同端口 而TCP却是可以同时运行natter和应用程序使用相同端口的，这个可以解决吗？

这个其实与 Windows 的 socket 特性有关，建议使用转发

**Comment by MikeWang000000** [comment]
目前最新 v2 版本已经正式支持 UDP，使用方法为 `-u` 选项。
如果遇到新的问题欢迎提新的 issue。
