### ISSUE TITLE
使用UDP协议遇到问题

### ISSUE THREAD

**Issue by zaiqixiao** [MikeWang000000/Natter#82]
### Discussed in https://github.com/MikeWang000000/Natter/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **zaiqixiao** April  9, 2024</sup>
![QQ截图20240411231555](https://github.com/MikeWang000000/Natter/assets/166514485/1206c8fd-80d5-4195-9b68-62fad6d17506)
![QQ截图20240411231635](https://github.com/MikeWang000000/Natter/assets/166514485/f5ccc2f6-f9ed-4f3b-a18f-e41e21bbdf8b)
![QQ截图20240411231720](https://github.com/MikeWang000000/Natter/assets/166514485/ee7a07d5-d508-443f-b331-edfa4c9bb33b)
![QQ截图20240411231737](https://github.com/MikeWang000000/Natter/assets/166514485/bb109992-374a-4149-8c11-599ebd027d3b)
TCP正常，但是UDP会卡在这里，请问要如何解决</div>

**Comment by Droid-MAX** [comment]
正常情况

**Comment by zaiqixiao** [comment]
> 正常情况

那请问udp没有回报，要从哪些地方开始排查解决

**Comment by Droid-MAX** [comment]
没有回报？response？客户端访问无响应？你指的是在natter上无响应还是服务端无响应？

**Comment by zaiqixiao** [comment]
> 没有回报？response？客户端访问无响应？你指的是在natter上无响应还是服务端无响应？

谢谢佬已经解决了，防火墙的问题。
