### ISSUE TITLE
the port is supposedly open but it is not possible to log in.

### ISSUE THREAD

**Issue by linnuxx** [MikeWang000000/Natter#83]
.

**Comment by linnuxx** [comment]
![ScreenShot_20240416225230](https://github.com/MikeWang000000/Natter/assets/154101918/36c01410-5743-4b23-86be-bc2c0022fc56)

**Comment by linnuxx** [comment]
![ScreenShot_20240416225443](https://github.com/MikeWang000000/Natter/assets/154101918/e944f49f-87ae-47e0-91fe-fea07575daa8)

**Comment by MikeWang000000** [comment]
Hello. Please check if your local address `http://192.168.1.155:37785` is accessible first.
Some Internet providers do block external HTTP requests, so you may also test with other protocols.

**Comment by MikeWang000000** [comment]
Closing this issue for lack of response.
