### ISSUE TITLE
[Feature Request]多IP出口选择

### ISSUE THREAD

**Issue by sumsethan** [MikeWang000000/Natter#9]
在一个具有多IP的设备上可能不同的src_addr走的是不同的线路，例如我这里情况：
```
root@HomePi:~# curl myip.ipip.net --interface 192.168.88.12
当前 IP：120.235.232.xx  来自于：中国 广东 广州  移动
root@HomePi:~# curl myip.ipip.net --interface eth0
当前 IP：120.235.232.xx  来自于：中国 广东 广州  移动
root@HomePi:~# curl myip.ipip.net --interface 192.168.88.13
当前 IP：119.34.xx.xx  来自于：中国 广东 广州  珠江宽频
root@HomePi:~# curl myip.ipip.net --interface eth0:1
当前 IP：119.34.xx.xx  来自于：中国 广东 广州  珠江宽频
```
在这种情况下是否可以添加一个例如 --interface 或者 -i 的参数让natter可以在不同的线路上打洞呢？谢谢！

**Comment by MikeWang000000** [comment]
目前已经支持，`python natter.py "IP地址" "端口号" `

**Comment by YYQHoro** [comment]
此PR将会变更为python natter.py -host "IP地址" "端口号"
https://github.com/MikeWang000000/Natter/pull/17

**Comment by sinaamos** [comment]
> 目前已经支持，`python natter.py "IP地址" "端口号" `

这里 IP地址是指定pppoe拨号获得的ISP内网IP吗

**Comment by MikeWang000000** [comment]
更新：v2.0 系列中可通过 `-i` 方式绑定 IP 或网络接口。
说明详见：https://github.com/MikeWang000000/Natter/blob/master/docs/usage.md
